### ISSUE TITLE
ElectionModule final cleanups

### ISSUE THREAD

**Issue by ajsantander** [Synthetixio/synthetix-v3#738]
### Tasks
- [x] Remove date vars in tests that don't need them
- [x] Move nomination logic to its own file?
- [x] Naming clean up: ensure no "voting", "nominating", "evaluating", etc in ElectionModule sources
- [x] No TODOs
- [x] Order of date parameters in schedule functions
- [x] Isn't it ugly that errors are all in ElectionBase?
- [x] Review gas efficiency. Don't destroy readability, but also don't be excessive
- [x] Nested structs at end
- [x] Consider getIdlePeriodDuration view
- [x] More tests for date changes with more extreme edge cases
- [x] Restore initializable checks in deployer (commented out until fixed)
- [x] Review reverts in view functions
- [x] Review external functions that just wrap an internal function without adding any value.
- [x] Review all uint sizes
- [x] Optimize packing in ElectionStorage
- [x] Clearly mark all contracts that are intended for override, and make sure they contain no generic logic or views
- [x] Review all comments
- [x] Only use internal in functions intended to be overriden in other contracts, and use virtual. Otherwise use private.
- [x] Simplify schedule. Multiple config functions are a bit confusing.
- [x] Review schedule adjustments again. Doesn't feel like the right solution.
- [x] Consider putting all test files in a folder and using shorter names
- [x] Make all views public? Some of them are already public.
- [x] Rename getCurrentPeriodType
